name: Build and Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'  # Use Node.js v20.11.1
          cache: 'npm'  # Caching npm dependencies to speed up builds

      - name: Install dependencies
        run: |
          npm install

      - name: Build Angular project
        run: |
          npm run build --prod  # Build the Angular project for production

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Create and push to deploy branch
        run: |
          # Ensure the deploy branch exists
          git fetch origin deploy:deploy || git checkout --orphan deploy
          # Remove all files from the deploy branch
          git rm -rf .
          # Copy the build output from dist/ to the deploy branch
          cp -r dist/* .
          git add .
          git commit -m "Deploy Angular app to GitHub Pages"
          git push origin deploy --force

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy  # The deploy branch
          folder: dist    # The folder containing the built Angular app
